### ISSUE TITLE
Quest: git fs support

### ISSUE THREAD

**Issue by lifeart** [lifeart/ember-language-server#317]
prev issue: https://github.com/lifeart/ember-language-server/issues/305

to get it working, likely we need:

- [ ] replace path with vscode path fallack (https://github.com/lifeart/ember-language-server/issues/304)

P.S. Finally figured out how to send global commands from extension server, likely one more related issue should be created:

- [x] to get it in addon api
- [ ] get list of all existing commands inside server
- [ ] provide vscode deps to addon api
- [ ] simplify existing commands proxy loop
- [ ] to get list of installed extensions https://github.com/lifeart/ember-language-server/issues/229
- [ ] autofix on save using code-action API https://github.com/lifeart/ember-language-server/issues/200

P.P.S Once we will be able to land it, we could start explore github repos usage (it's editor for hotkey `.`), and automatically "install" nessesary addons using fetch API into virtual FS.

https://github.com/0xGG/vscode-web-fs/blob/master/src/extension.ts
