### ISSUE TITLE
Quest [glimmerx] support

### ISSUE THREAD

**Issue by lifeart** [lifeart/ember-language-server#324]
- [ ] collect global variables from templates https://github.com/lifeart/ember-language-server/issues/321
- [x] check ember-template-lint integration https://github.com/lifeart/ember-language-server/issues/322
- [x] update prettier extension https://github.com/prettier/prettier-vscode/pull/2246
- [x] get default formatting working by https://github.com/lifeart/typescript-hbs-plugin
- [x] add `<template>` formatting suppor in glimmer syntax https://github.com/lifeart/vsc-ember-syntax
- [x] add hover provider into addon API https://github.com/lifeart/ember-language-server/pull/327
- [x] fix position argument mutation https://github.com/lifeart/ember-language-server/pull/333
- [ ] add completion resolve provider into addon API
- [ ] update glint addon to use uELS hover provider API
- [ ] add "document" object to project level (proxy from server)
- [ ] fix glint support https://github.com/lifeart/ember-language-server/issues/209

**Comment by lifeart** [comment]
https://code.visualstudio.com/api/language-extensions/embedded-languages
